#include "ordenacao.h"
//ORDENAR UM VETOR DE ALUNOS PELA MATRÍCULA
//DICAS: OLHAR TALUNO.H
//TAMANHO MÁXIMO E MÍNIMO DO VETOR É DA DEFINIÇÃO TO TAMANHO DE UMA PÁGINA DA ÁRVORE B
//PARÂMETROS PODEM SER UMA PÁGINA, DEFINIDA EM ArvoreB.H, ou Simplesmente um vetor de TALUNOS
